In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [8]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [14]:
x_ones = torch.rand_like(x_data, dtype=torch.float)
x_ones = torch.rand_like(x_data.float())
x_ones

tensor([[0.4282, 0.4909],
        [0.7506, 0.5256]])

In [16]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.8559, 0.0380, 0.5333],
         [0.4751, 0.9181, 0.3447]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [18]:
t = rand_tensor
t.shape, t.dtype, t.device

(torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [20]:
if torch.cuda.is_available():
    t = t.to("cuda")
    print("Moved to cuda")
else:
    print("No GPU!")

No GPU!


In [30]:
t = torch.rand((4, 4))
t

tensor([[0.3951, 0.0701, 0.7018, 0.8951],
        [0.2607, 0.5104, 0.7584, 0.6686],
        [0.9517, 0.4718, 0.5497, 0.4948],
        [0.1961, 0.1184, 0.7166, 0.4292]])

In [31]:
# First row
t[0]

tensor([0.3951, 0.0701, 0.7018, 0.8951])

In [32]:
# First column
t[:, 0]

tensor([0.3951, 0.2607, 0.9517, 0.1961])

In [33]:
# Last column
t[:, -1]

tensor([0.8951, 0.6686, 0.4948, 0.4292])

In [34]:
t[:, 1] = 0
t

tensor([[0.3951, 0.0000, 0.7018, 0.8951],
        [0.2607, 0.0000, 0.7584, 0.6686],
        [0.9517, 0.0000, 0.5497, 0.4948],
        [0.1961, 0.0000, 0.7166, 0.4292]])

In [36]:
t1 = torch.rand(3, 4)
t2 = torch.rand(3, 4)
t1, t2

(tensor([[0.7987, 0.4745, 0.0889, 0.7845],
         [0.4590, 0.4003, 0.1968, 0.6774],
         [0.7720, 0.3571, 0.2297, 0.0640]]),
 tensor([[0.7583, 0.8256, 0.7232, 0.0128],
         [0.8445, 0.4238, 0.4492, 0.3906],
         [0.8416, 0.4186, 0.0192, 0.6513]]))

In [37]:
torch.cat([t1, t2])  # axis=0

tensor([[0.7987, 0.4745, 0.0889, 0.7845],
        [0.4590, 0.4003, 0.1968, 0.6774],
        [0.7720, 0.3571, 0.2297, 0.0640],
        [0.7583, 0.8256, 0.7232, 0.0128],
        [0.8445, 0.4238, 0.4492, 0.3906],
        [0.8416, 0.4186, 0.0192, 0.6513]])

In [38]:
torch.cat([t1, t2], axis=1)

tensor([[0.7987, 0.4745, 0.0889, 0.7845, 0.7583, 0.8256, 0.7232, 0.0128],
        [0.4590, 0.4003, 0.1968, 0.6774, 0.8445, 0.4238, 0.4492, 0.3906],
        [0.7720, 0.3571, 0.2297, 0.0640, 0.8416, 0.4186, 0.0192, 0.6513]])

In [44]:
torch.stack([t1, t2])

tensor([[[0.7987, 0.4745, 0.0889, 0.7845],
         [0.4590, 0.4003, 0.1968, 0.6774],
         [0.7720, 0.3571, 0.2297, 0.0640]],

        [[0.7583, 0.8256, 0.7232, 0.0128],
         [0.8445, 0.4238, 0.4492, 0.3906],
         [0.8416, 0.4186, 0.0192, 0.6513]]])

### Notes

Stack with axis is extremely confusing... Basically, the size of that
axis in the resulting tensor equals the number of stacked elements

In [45]:
t

tensor([[0.3951, 0.0000, 0.7018, 0.8951],
        [0.2607, 0.0000, 0.7584, 0.6686],
        [0.9517, 0.0000, 0.5497, 0.4948],
        [0.1961, 0.0000, 0.7166, 0.4292]])

In [50]:
y1 = t @ t.T  # matmul!
y2 = t.matmul(t.T)
assert((y1 == y2).all())
y1

tensor([[1.4497, 1.2337, 1.2046, 0.9645],
        [1.2337, 1.0902, 0.9957, 0.8815],
        [1.2046, 0.9957, 1.4526, 0.7928],
        [0.9645, 0.8815, 0.7928, 0.7362]])

In [55]:
z1 = t * t  # elementwise mul (Hadamard product)
z2 = t.mul(t)
z3 = torch.rand_like(t)
torch.mul(t, t, out=z3)
assert((z1 == z2).all())
assert((z1 == z3).all())
z3

tensor([[0.1561, 0.0000, 0.4925, 0.8011],
        [0.0679, 0.0000, 0.5751, 0.4471],
        [0.9057, 0.0000, 0.3021, 0.2448],
        [0.0385, 0.0000, 0.5135, 0.1842]])

In [57]:
agg = t.sum()
agg, agg.item()

(tensor(7.0176), 7.017580032348633)

### In-place operations!

- Functions with _ suffixes (oh!).
- Noted in the docs that these operations may lead to loss of history.
  - Q. why?

In [58]:
t

tensor([[0.3951, 0.0000, 0.7018, 0.8951],
        [0.2607, 0.0000, 0.7584, 0.6686],
        [0.9517, 0.0000, 0.5497, 0.4948],
        [0.1961, 0.0000, 0.7166, 0.4292]])

In [59]:
t.add_(5)

tensor([[5.3951, 5.0000, 5.7018, 5.8951],
        [5.2607, 5.0000, 5.7584, 5.6687],
        [5.9517, 5.0000, 5.5497, 5.4948],
        [5.1961, 5.0000, 5.7166, 5.4292]])

In [60]:
t

tensor([[5.3951, 5.0000, 5.7018, 5.8951],
        [5.2607, 5.0000, 5.7584, 5.6687],
        [5.9517, 5.0000, 5.5497, 5.4948],
        [5.1961, 5.0000, 5.7166, 5.4292]])

In [61]:
t.add(5)
t

tensor([[5.3951, 5.0000, 5.7018, 5.8951],
        [5.2607, 5.0000, 5.7584, 5.6687],
        [5.9517, 5.0000, 5.5497, 5.4948],
        [5.1961, 5.0000, 5.7166, 5.4292]])

In [63]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [64]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [65]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [74]:
n = np.ones(5)
t1 = torch.from_numpy(n)
t2 = torch.tensor(n)
assert(t1.equal(t2))
n, t1

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [75]:
np.add(n, 1, out=n)
n, t1

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

### Notes

- Numpy and torch tensors share memory by default
- Must be pretty dirty when you move around CPU and GPU...
  - TODO (on GPU)