In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_ones = torch.rand_like(x_data, dtype=torch.float)
x_ones = torch.rand_like(x_data.float())
x_ones

tensor([[0.0465, 0.8464],
        [0.6291, 0.6108]])

In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.7980, 0.4973, 0.8979],
         [0.2375, 0.1454, 0.4570]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [7]:
t = rand_tensor
t.shape, t.dtype, t.device

(torch.Size([2, 3]), torch.float32, device(type='cpu'))

In [8]:
if torch.cuda.is_available():
    t = t.to("cuda")
    print("Moved to cuda")
else:
    print("No GPU!")

Moved to cuda


In [9]:
t = torch.rand((4, 4))
t

tensor([[0.4556, 0.8010, 0.4316, 0.9551],
        [0.1984, 0.2237, 0.9466, 0.1117],
        [0.6028, 0.1022, 0.7670, 0.1570],
        [0.5611, 0.1102, 0.0268, 0.2399]])

In [10]:
# First row
t[0]

tensor([0.4556, 0.8010, 0.4316, 0.9551])

In [11]:
# First column
t[:, 0]

tensor([0.4556, 0.1984, 0.6028, 0.5611])

In [12]:
# Last column
t[:, -1]

tensor([0.9551, 0.1117, 0.1570, 0.2399])

In [13]:
t[:, 1] = 0
t

tensor([[0.4556, 0.0000, 0.4316, 0.9551],
        [0.1984, 0.0000, 0.9466, 0.1117],
        [0.6028, 0.0000, 0.7670, 0.1570],
        [0.5611, 0.0000, 0.0268, 0.2399]])

In [14]:
t1 = torch.rand(3, 4)
t2 = torch.rand(3, 4)
t1, t2

(tensor([[0.5873, 0.0422, 0.5207, 0.4625],
         [0.4345, 0.5271, 0.6636, 0.4851],
         [0.7973, 0.0403, 0.7699, 0.3223]]),
 tensor([[0.9521, 0.6872, 0.1392, 0.0221],
         [0.8481, 0.8614, 0.2884, 0.5352],
         [0.5055, 0.6557, 0.0872, 0.3869]]))

In [15]:
torch.cat([t1, t2])  # axis=0

tensor([[0.5873, 0.0422, 0.5207, 0.4625],
        [0.4345, 0.5271, 0.6636, 0.4851],
        [0.7973, 0.0403, 0.7699, 0.3223],
        [0.9521, 0.6872, 0.1392, 0.0221],
        [0.8481, 0.8614, 0.2884, 0.5352],
        [0.5055, 0.6557, 0.0872, 0.3869]])

In [16]:
torch.cat([t1, t2], axis=1)

tensor([[0.5873, 0.0422, 0.5207, 0.4625, 0.9521, 0.6872, 0.1392, 0.0221],
        [0.4345, 0.5271, 0.6636, 0.4851, 0.8481, 0.8614, 0.2884, 0.5352],
        [0.7973, 0.0403, 0.7699, 0.3223, 0.5055, 0.6557, 0.0872, 0.3869]])

In [17]:
torch.stack([t1, t2])

tensor([[[0.5873, 0.0422, 0.5207, 0.4625],
         [0.4345, 0.5271, 0.6636, 0.4851],
         [0.7973, 0.0403, 0.7699, 0.3223]],

        [[0.9521, 0.6872, 0.1392, 0.0221],
         [0.8481, 0.8614, 0.2884, 0.5352],
         [0.5055, 0.6557, 0.0872, 0.3869]]])

### Notes

Stack with axis is extremely confusing... Basically, the size of that
axis in the resulting tensor equals the number of stacked elements

In [18]:
t

tensor([[0.4556, 0.0000, 0.4316, 0.9551],
        [0.1984, 0.0000, 0.9466, 0.1117],
        [0.6028, 0.0000, 0.7670, 0.1570],
        [0.5611, 0.0000, 0.0268, 0.2399]])

In [19]:
y1 = t @ t.T  # matmul!
y2 = t.matmul(t.T)
assert((y1 == y2).all())
y1

tensor([[1.3060, 0.6056, 0.7556, 0.4963],
        [0.6056, 0.9479, 0.8632, 0.1635],
        [0.7556, 0.8632, 0.9763, 0.3965],
        [0.4963, 0.1635, 0.3965, 0.3730]])

In [20]:
z1 = t * t  # elementwise mul (Hadamard product)
z2 = t.mul(t)
z3 = torch.rand_like(t)
torch.mul(t, t, out=z3)
assert((z1 == z2).all())
assert((z1 == z3).all())
z3

tensor([[2.0761e-01, 0.0000e+00, 1.8624e-01, 9.1213e-01],
        [3.9362e-02, 0.0000e+00, 8.9607e-01, 1.2479e-02],
        [3.6339e-01, 0.0000e+00, 5.8828e-01, 2.4652e-02],
        [3.1478e-01, 0.0000e+00, 7.2071e-04, 5.7530e-02]])

In [21]:
agg = t.sum()
agg, agg.item()

(tensor(5.4536), 5.453556537628174)

### In-place operations!

- Functions with _ suffixes (oh!).
- Noted in the docs that these operations may lead to loss of history.
  - Q. why?

In [22]:
t

tensor([[0.4556, 0.0000, 0.4316, 0.9551],
        [0.1984, 0.0000, 0.9466, 0.1117],
        [0.6028, 0.0000, 0.7670, 0.1570],
        [0.5611, 0.0000, 0.0268, 0.2399]])

In [23]:
t.add_(5)

tensor([[5.4556, 5.0000, 5.4316, 5.9551],
        [5.1984, 5.0000, 5.9466, 5.1117],
        [5.6028, 5.0000, 5.7670, 5.1570],
        [5.5611, 5.0000, 5.0268, 5.2399]])

In [24]:
t

tensor([[5.4556, 5.0000, 5.4316, 5.9551],
        [5.1984, 5.0000, 5.9466, 5.1117],
        [5.6028, 5.0000, 5.7670, 5.1570],
        [5.5611, 5.0000, 5.0268, 5.2399]])

In [25]:
t.add(5)
t

tensor([[5.4556, 5.0000, 5.4316, 5.9551],
        [5.1984, 5.0000, 5.9466, 5.1117],
        [5.6028, 5.0000, 5.7670, 5.1570],
        [5.5611, 5.0000, 5.0268, 5.2399]])

In [26]:
t = torch.ones(5)
t

tensor([1., 1., 1., 1., 1.])

In [27]:
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [28]:
t.add_(1)
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [29]:
n = np.ones(5)
t1 = torch.from_numpy(n)
t2 = torch.tensor(n)
assert(t1.equal(t2))
n, t1

(array([1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [30]:
np.add(n, 1, out=n)
n, t1

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

### Notes

- Numpy and torch tensors share memory by default
- Must be pretty dirty when you move around CPU and GPU...
  - TODO (on GPU)

In [32]:
n = np.ones(5)
tn = torch.from_numpy(n)
t = torch.tensor(n)

In [33]:
np.add(n, 1, out=n)

array([2., 2., 2., 2., 2.])

In [34]:
tn, t

(tensor([2., 2., 2., 2., 2.], dtype=torch.float64),
 tensor([1., 1., 1., 1., 1.], dtype=torch.float64))

In [46]:
tg = tn.to("cuda")

In [47]:
tg.add_(1)

tensor([3., 3., 3., 3., 3.], device='cuda:0', dtype=torch.float64)

In [48]:
tn

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [49]:
n

array([2., 2., 2., 2., 2.])

In [50]:
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [51]:
tnn = tg.to("cpu")

In [52]:
tnn

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)

In [53]:
tnn.add_(1)

tensor([4., 4., 4., 4., 4.], dtype=torch.float64)

In [54]:
tg

tensor([3., 3., 3., 3., 3.], device='cuda:0', dtype=torch.float64)

### GPU Results

- As expected, CPU/GPU tensors are independent (always copy).