In [16]:
import torch
import pandas as pd
import numpy as np

from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision.transforms import ToTensor, Lambda

### Notes

- ToTensor: converts PIL.Image or np.ndarray into torch.tensor! (wow)
- Lambda: lambda! (you can do stuff like one-hot as below)

- Note that these functions in the data loading pipeline do not need autograd,
  but they would ought to be parallelizable.
  - Q. Are they?

In [8]:
one_hot = lambda y: torch.zeros(10).float().scatter_(0, torch.tensor(y), value=1)
one_hot(1), one_hot(2), one_hot(3)

(tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]))

In [11]:
train_ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    target_transform=Lambda(one_hot),
)

In [14]:
next(iter(train_ds))[0].shape

torch.Size([1, 28, 28])

In [15]:
next(iter(train_ds))[1].shape

torch.Size([10])

In [18]:
train_loader = DataLoader(train_ds, batch_size=64)

### End of Tutorial

Well that was short...